server:
  port: 8080

spring:
  profiles:
    active: default
  application:
    name: user
  config:
    import: optional:file:.env[.properties]

interview-bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}


